// theme.jsx - Three distinct design directions for Deimos
// Each direction has light + dark variants

const THEMES = {
  instrument: {
    name: 'Instrument',
    tagline: 'Technical · Data-forward · Terminal',
    light: {
      bg: '#f5f3ee',
      surface: '#ffffff',
      surface2: '#ecebe4',
      border: '#d9d6cb',
      borderStrong: '#19181a',
      text: '#19181a',
      textDim: '#6a6a6a',
      textMuted: '#8a8a8a',
      accent: '#e9492f',     // vermilion
      accent2: '#0f766e',    // teal
      success: '#0f766e',
      warn: '#b45309',
      chrome: '#19181a',
      onChrome: '#f5f3ee',
      chip: '#19181a',
      onChip: '#f5f3ee',
      grid: 'rgba(25,24,26,0.07)',
    },
    dark: {
      bg: '#0d0d0e',
      surface: '#171719',
      surface2: '#222226',
      border: '#2b2b30',
      borderStrong: '#f5f3ee',
      text: '#f5f3ee',
      textDim: '#a8a8a8',
      textMuted: '#6a6a6a',
      accent: '#ff6a4d',
      accent2: '#5eead4',
      success: '#5eead4',
      warn: '#fbbf24',
      chrome: '#f5f3ee',
      onChrome: '#0d0d0e',
      chip: '#f5f3ee',
      onChip: '#0d0d0e',
      grid: 'rgba(245,243,238,0.06)',
    },
    fontDisplay: '"JetBrains Mono", ui-monospace, monospace',
    fontBody: '"Inter Tight", system-ui, sans-serif',
    fontMono: '"JetBrains Mono", ui-monospace, monospace',
    radius: 4,
    radiusCard: 8,
  },

  editorial: {
    name: 'Editorial',
    tagline: 'Warm · Serif · Website-matched',
    light: {
      bg: '#efeae0',
      surface: '#f7f2e8',
      surface2: '#e6dfd1',
      border: '#d4cbb9',
      borderStrong: '#2a231a',
      text: '#2a231a',
      textDim: '#6b5e4a',
      textMuted: '#8a7d68',
      accent: '#8b5cf6',     // muted violet to hint at current brand
      accent2: '#b45309',
      success: '#4d7c3e',
      warn: '#b45309',
      chrome: '#2a231a',
      onChrome: '#efeae0',
      chip: '#2a231a',
      onChip: '#efeae0',
      grid: 'rgba(42,35,26,0.06)',
    },
    dark: {
      bg: '#1b1813',
      surface: '#24201a',
      surface2: '#2f2a22',
      border: '#3a352c',
      borderStrong: '#efeae0',
      text: '#efeae0',
      textDim: '#b5ab95',
      textMuted: '#8a7d68',
      accent: '#c4b5fd',
      accent2: '#f59e0b',
      success: '#86c17a',
      warn: '#f59e0b',
      chrome: '#efeae0',
      onChrome: '#1b1813',
      chip: '#efeae0',
      onChip: '#1b1813',
      grid: 'rgba(239,234,224,0.05)',
    },
    fontDisplay: '"Instrument Serif", "Cormorant Garamond", Georgia, serif',
    fontBody: '"Inter", system-ui, sans-serif',
    fontMono: '"JetBrains Mono", ui-monospace, monospace',
    radius: 12,
    radiusCard: 20,
  },

  neomaterial: {
    name: 'Neo-Material',
    tagline: 'Modern · Soft · Consumer-friendly',
    light: {
      bg: '#f1f4f8',
      surface: '#ffffff',
      surface2: '#e7ecf3',
      border: '#dde3ec',
      borderStrong: '#0e1a2b',
      text: '#0e1a2b',
      textDim: '#536075',
      textMuted: '#8a93a4',
      accent: '#3a5bff',
      accent2: '#00b894',
      success: '#00b894',
      warn: '#f59e0b',
      chrome: '#0e1a2b',
      onChrome: '#ffffff',
      chip: '#3a5bff',
      onChip: '#ffffff',
      grid: 'rgba(14,26,43,0.05)',
    },
    dark: {
      bg: '#0a0f1a',
      surface: '#111827',
      surface2: '#1b2435',
      border: '#243042',
      borderStrong: '#ffffff',
      text: '#e7ecf3',
      textDim: '#94a0b5',
      textMuted: '#6b7689',
      accent: '#6b85ff',
      accent2: '#34d399',
      success: '#34d399',
      warn: '#fbbf24',
      chrome: '#ffffff',
      onChrome: '#0a0f1a',
      chip: '#6b85ff',
      onChip: '#0a0f1a',
      grid: 'rgba(255,255,255,0.04)',
    },
    fontDisplay: '"Space Grotesk", system-ui, sans-serif',
    fontBody: '"Inter", system-ui, sans-serif',
    fontMono: '"JetBrains Mono", ui-monospace, monospace',
    radius: 14,
    radiusCard: 24,
  },
};

window.THEMES = THEMES;
